[workspace]
authors = ["Esteve Fernandez <esteve@apache.org>"]
channels = ["https://prefix.dev/robostack-jazzy", "https://prefix.dev/conda-forge"]
name = "ros_ws"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
build = "colcon build"

[dependencies]
ros-jazzy-ros2run = ">=0.32.6,<0.33"
ros-jazzy-ament-cmake-ros = "*"
ros-jazzy-ament-cmake = "*"
ros-jazzy-ament-lint-auto = "*"
ros-jazzy-ament-lint-common = "*"
colcon-common-extensions = "*"
compilers = "*"
cmake = "*"
ninja = "*"
pkg-config = "*"

[activation]
scripts = ["install/setup.sh"]
